### ISSUE TITLE
react-router-dom v6+ har byttet ut useHistory med useNavigate.

### ISSUE THREAD

**Issue by sindredl** [navikt/bedriftsmeny#76]
Vi oppgraderte nettopp endel av pakkene i en av appene våre, blant annet `react-router-dom`. Denne er nå på versjon 6, som har endel breaking (men bra) changes i apiet.

En av endringene er at `history` og `useHistory` er byttet ut med `navigate` og `useNavigate`. Bedriftsmenyen tar inn `history` som en obligatorisk prop og dermed vil ikke Bedriftsmenyen fungere.

Her er mer om endringene til navigate: https://reactrouter.com/docs/en/v6/upgrading/v5#use-usenavigate-instead-of-usehistory

En mulighet er kanskje bare å bruke `useHistory` internt i Bedriftsmenyen slik at dette ikke trengs å proppes inn? Hvis det er mulig vil det også gjøre at brukere av Bedriftsmenyen blir mindre låst til versjon x av react-router-dom.
En annen mulighet er å oppgradere til useNavigate, men det er vel mer jobb og også kreve at brukere av bedriftsmenyen oppgraderer til react-router v6+..

Vi har laget en liten midlertidig fix på det som ser ut til å fungere: 
https://github.com/navikt/tiltak-refusjon-arbeidsgiver/blob/a064e64d2aad04911b73794ac1a32839a035696c/src/refusjon/Banner.tsx

Ta gjerne kontakt for en diskusjon/mer info :)

**Comment by kenglxn** [comment]
fikset i https://github.com/navikt/bedriftsmeny/releases/tag/v4.0.0
